namespace PlanetGauge
{
    internal static class EnglishStrings
    {
        internal const string MainGaugeSize = "Main gauge size";
        internal const string Scale = "Scale";
        internal const string Width = "Width";
        internal const string ResetSize = "Reset size";
        internal const string CustomGaugeSkin = "Custom gauge skin";
        internal const string HealthPng = "Health PNG: {0}";
        internal const string SelectHealthPng = "Select health PNG";
        internal const string ClearHealthPng = "Clear health PNG";
        internal const string SelectHealthPngDialog = "Select PlanetGauge health PNG";
        internal const string FramePngOptional = "Frame PNG (optional): {0}";
        internal const string SelectFramePng = "Select frame PNG";
        internal const string ClearFramePng = "Clear frame PNG";
        internal const string SelectFramePngDialog = "Select optional PlanetGauge frame PNG";
        internal const string FillDirection = "Fill direction";
        internal const string HorizontalFill = "Horizontal (left to right)";
        internal const string VerticalFill = "Vertical (bottom to top)";
        internal const string FrameOffset = "Frame offset";
        internal const string FrameX = "Frame X";
        internal const string FrameY = "Frame Y";
        internal const string ResetFrameOffset = "Reset frame offset";
        internal const string ApplyCustomSkin = "Apply custom skin";
        internal const string UseDefaultSkin = "Use default skin";
        internal const string Warning = "Warning: {0}";
        internal const string MainGaugePosition = "Main gauge position";
        internal const string ResetPosition = "Reset position";
        internal const string GaugeValueText = "Gauge value text";
        internal const string TextSize = "Text size";
        internal const string IndependentPosition = "Independent position";
        internal const string TextX = "Text X";
        internal const string TextY = "Text Y";
        internal const string ResetTextPosition = "Reset text position";
        internal const string AttributeText = "Attribute text";
        internal const string AttributeSize = "Attribute size";
        internal const string AttributeX = "Attribute X";
        internal const string AttributeY = "Attribute Y";
        internal const string ResetAttributePosition = "Reset attribute position";
        internal const string RateToken = "Rate token";
        internal const string RateSize = "Rate size";
        internal const string RateX = "Rate X";
        internal const string RateY = "Rate Y";
        internal const string ResetRatePosition = "Reset rate position";
        internal const string Advanced = "Advanced";
        internal const string ShowDecimalHealth = "Show decimal health (e.g. 73.4)";
        internal const string MainGaugeColor = "Main gauge color (RGB)";
        internal const string ResetColor = "Reset color (#FFFFFF)";
        internal const string DebugShortcut = "Debug shortcut: {0} + {1}";
        internal const string SetKey1 = "Set key 1";
        internal const string SetKey2 = "Set key 2";
        internal const string PressKey1 = "Press key 1 (Escape to cancel)";
        internal const string PressKey2 = "Press key 2 (Escape to cancel)";
        internal const string ResetShortcut = "Reset shortcut";
        internal const string KeysMustDiffer = "Key 1 and key 2 must be different.";
        internal const string None = "None";
        internal const string PixelUnit = "px";
        internal const string TranslateAttributeDisplay = "Translate attribute display to Korean";

        internal const string Blindfolded = "Blindfolded";
        internal const string IncreaseDisabled = "Increase Disabled";
        internal const string RateReduced = "Rate Reduced";
        internal const string RateAmplified = "Rate Amplified";
        internal const string Increase = "Increase";
        internal const string Decrease = "Decrease";
        internal const string NoFailDisabled = "No-Fail Disabled";
        internal const string IncreaseLimited = "Increase Limited";
        internal const string ReducedEffect = "{0} Reduced";
        internal const string AmplifiedEffect = "{0} Amplified";

        internal const string GaugeEnabled = "PlanetGauge enabled";
        internal const string GaugeDisabled = "PlanetGauge disabled";
        internal const string PngImage = "PNG Image";
        internal const string FileSelectionFailed = "File selection failed: {0}";
        internal const string SelectHealthPngFirst = "Select a health PNG first.";
        internal const string SkinLoadsWhenEnabled = "The selected skin will load when the mod is enabled.";
        internal const string CustomSkinApplied = "Custom gauge skin applied.";
        internal const string SkinApplyFailed = "Failed to apply skin: {0}";
        internal const string UsingDefaultSkin = "Using the default gauge skin.";
        internal const string HealthPngAsset = "Health PNG";
        internal const string FramePngAsset = "Frame PNG";
        internal const string FileNotFound = "{0} file was not found.";
        internal const string FileMustBePng = "{0} must be a PNG file.";
        internal const string ImageVeryLarge = "{0} is very large ({1}x{2}, file {3} MiB, RGBA {4} MiB). Memory usage may increase significantly.";
        internal const string TextureConversionFailed = "Could not convert {0} to a Unity Texture2D.";
        internal const string ImageFullyTransparent = "{0} is fully transparent.";
        internal const string LoadImageMethodMissing = "UnityEngine.ImageConversion.LoadImage(Texture2D, byte[], bool) was not found.";
        internal const string PngHeaderTooShort = "The PNG header is too short.";
        internal const string PngSignatureInvalid = "The PNG signature is invalid.";
        internal const string PngIhdrMissing = "The PNG IHDR chunk was not found.";
        internal const string PngDimensionsInvalid = "The PNG dimensions are invalid.";

        internal const string MultiplierReuseNote = "When disabled, the last value configured for this attribute is used.";
        internal const string RecoveryAmountNote = "A negative value decreases health.\nRecovery above the maximum health is discarded.";
        internal const string GaugeEventName = "PlanetGauge settings";
        internal const string SkinEventName = "PlanetGauge skin";
        internal const string Horizontal = "Horizontal";
        internal const string Vertical = "Vertical";
        internal const string Normal = "Normal";
        internal const string BlockRecovery = "Block recovery";
        internal const string AmplifyDecrease = "Change decrease rate";
        internal const string AmplifyIncrease = "Change increase rate";
        internal const string AmplifyBoth = "Change increase/decrease rate";
        internal const string Blindfold = "Hide health";
        internal const string ForceRecovery = "Force health recovery";
        internal const string HideGaugeHud = "Hide gauge HUD";

        internal const string AttributeModeLabel = "Attribute settings";
        internal const string AttributeEnabledLabel = "Enable selected attribute";
        internal const string DisableOtherAttributesLabel = "Disable other attribute settings";
        internal const string HideGaugeBarLabel = "Hide gauge bar";
        internal const string HideGaugeValueLabel = "Hide health value";
        internal const string HideAttributeTextLabel = "Hide active attribute text";
        internal const string HideRateTokenLabel = "Hide rate token";
        internal const string HideForceRecoveryVisualsLabel = "Hide force recovery visuals";
        internal const string MultiplierPercentLabel = "Set change value";
        internal const string RecoveryAmountLabel = "Set recovery amount";
        internal const string WarningOffsetLabel = "Warning angle offset";
        internal const string WarningPulseLabel = "Pulse interval";
        internal const string FailureProtectionLabel = "Failure protection";
        internal const string RecoveryCapEnabledLabel = "Enable recovery cap";
        internal const string RecoveryCapLabel = "Recovery cap";
        internal const string ForceRecoveryCapLabel = "Force health cap";
        internal const string AutoTileRecoveryLabel = "Autoplay tile recovery";
        internal const string TargetTagLabel = "Target tag";
        internal const string SkinEnabledLabel = "Enabled";
        internal const string GaugeTypeLabel = "Gauge type";

        internal const string DebugGaugeLine = "Gauge: {0} / {1}  BaseMax: {2}";
        internal const string DebugRatesLine = "Recovery: {0}  Damage: {1}";
        internal const string DebugAttributesLine = "BlockRecovery: {0}  Blindfold: {1}  Revealed: {2}";
        internal const string DebugFailureProtectionLine = "FailureProtection: {0}";
        internal const string DebugRecoveryCapLine = "RecoveryCap: {0} @ {1}  AutoTileRecovery: {2}";
        internal const string DebugPlaybackLine = "ActualAutoPlay: {0}  Paused: {1}";
        internal const string DebugRuntimeLine = "Frozen: {0}  RecoveryDepth: {1}  PendingDie: {2}  ForcingDeath: {3}";
        internal const string DebugActiveLine = "Active: {0}";
        internal const string DebugHudHiddenLine = "HUD TargetHidden: Bar={0} Value={1} Attribute={2} Rate={3} Force={4}";
        internal const string DebugHudAlphaLine = "HUD Alpha: Bar={0} Value={1} Attribute={2} Rate={3} Force={4}";
        internal const string DebugSkinLine = "Skin: {0}";
        internal const string DebugSkinProgressLine = "SkinProgress: {0}  FrameOffset: {1},{2}  ForceOverlay: Disabled";
        internal const string DebugDecorationSkinLine = "DecorationSkin: {0}  Tags={1}  Images={2}  Legacy={3}  Alpha={4}  Progress={5}";
        internal const string DebugTotals = "Totals (applied)";
        internal const string DebugAuto = "Auto";
        internal const string DebugDefaultRate = "Default 100%";
        internal const string DebugActiveBlockRecovery = "BlockRecovery";
        internal const string DebugActiveRecoveryRate = "RecoveryRate";
        internal const string DebugActiveDamageRate = "DamageRate";
        internal const string DebugActiveBlindfold = "Blindfold";
        internal const string DebugActiveNoFailDisabled = "NoFailDisabled";
        internal const string DebugActiveRecoveryCap = "RecoveryCap";
        internal const string DebugActiveAutoTileRecovery = "AutoTileRecovery";
        internal const string DebugActiveHideGaugeHud = "HideGaugeHud";
        internal const string DefaultSkinDescription = "Default";
        internal const string CustomSkinDescription = "Custom {0} Health={1}x{2} Bounds={3}{4}";
        internal const string NoFrameDescription = " Frame=None";
        internal const string FrameDescription = " Frame={0}x{1} Bounds={2}";
        internal const string Pending = "Pending";
    }
}
