<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <GameManagedDir Condition="'$(GameManagedDir)' == ''">G:\SteamLibrary\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed</GameManagedDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../PlanetGauge/Patches.cs" Link="Patches.cs" />
    <Compile Include="../../PlanetGauge/VanillaJudgementObservation.cs" Link="VanillaJudgementObservation.cs" />
    <Reference Include="0Harmony">
      <HintPath>$(GameManagedDir)/UnityModManager/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
